
# **DISTRIBUTION**

Distribution of calanoid copepods in the China seas is strongly affected by the oceanic currents (<a class="fbox" href="img/text-fig002.jpg" data-alt="" />text-fig. 2</a>) and the East Asian seasonal monsoons.  Monsoon changes wind direction, northeasterly in October to April and southwesterly in the remainder of the year, and therefore affects the direction and strength of oceanic currents.

The North Equatorial Current in the Pacific Ocean travels westward near Equator, runs into the Philippine coast, and divides into two branches: the northward Kuroshio and southward Mindanao currents. The Kuroshio, a western boundary current of the North Pacific and equivalent to the Gulf Stream in the North Atlantic Ocean, flows northward along the east coast of Taiwan and continental slope of the East China Sea, and finally turns northeastward then eastward to travel south of Japan (Qiu et al., 2015).  Along its northward path, the Kuroshio makes three westward intrusions, from south to north, 1) through the Luzon Strait into the South China Sea and Taiwan Strait, 2) through a sill between the Taiwan island and southwestern end of the Ryukyu Islands into the southern East China Sea, 3) at the continental slope southwest of Kyushu into the northern East China Sea (Lie & Cho, 2016)

All China seas, except the South China Sea, are shallow and mostly limited to continental shelf. The South China Sea has an average depth of 1,200 meters.  Hu et al (2000) reviewed the oceanic circulation in the South China Sea.  According to Fang et al. (1998), the South China Sea has four major currents in the 0-400 m layer, i.e., the Nansha Western Coastal Current (NWCC), the Nansha Eastern Coastal Current (NECC), the North Nansha Current (NNC), and the Nansha Counter-wind Current (NCC), which (except NECC) are significantly affected by monsoons.  In the northeastern South China Sea a northeastward counter-wind current, the South China Sea Warm Current (SCSWC), is a strong and narrow current throughout winter in the open sea off the Guangdong Province.  It extends northward along the west coast of the southern Taiwan Strait in summer (Hu and Liu 1992).  While travelling northward, a branch of the Kuroshio penetrates through Luzon Strait into the South China Sea. This Kuroshio intrusion has impact on copepod distribution in the South China Sea and Taiwan Strait.

Taiwan Strait is a shallow passage, 60 m in average depth, between the island of Taiwan on the east and mainland China on the west and connects the South China Sea to the East China Sea.  The southward China Coastal Current (CCC) dominants on the west of the Strait and, on the east, the two northward currents, South China Sea Warm Current (SCSWC) dominates in summer and Kuroshio Branch Current (KBC) dominates in other seasons. These currents are heavily influenced by the forcing of annual cycle of monsoons, reinforcing the northward currents in summer but southward current in other seasons (Jan et al. 2002).

The oceanic circulation in the East China Sea and Yellow Sea is basically composed of two systems: 1) on the east and northward flowing: Kuroshio in the Okinawa Trough and its two branches (Western Kuroshio Branch, WKB and Eastern Kuroshio Branch, EKB) over the outer shelf and 2) on the west and southward flowing in winter and weakening or changing to northward flowing in summer: the China Coastal Current (a general term for all coastal currents along Chinese coast, e.g., Bohai Sea Coastal current, Yellow Sea Coastal Current, Jiangsu Coastal Current, Zhejian-Fujian Coastal Current, Yuedong Coastal Current) along the east coast and over inner and middle shelves (Lie & Cho, 2016).

Western Kuroshio Branch (WKB) is born at the continental slope northeast of Taiwan to carry Kuroshio water to the western East China Sea shelf.  Eastern Kuroshio Branch (EKB) is born at continental slope southwest of Kyushu to carry Kuroshio water to the eastern East China Sea shelf.  Its secondary branches south of Jeju-do include: 1: Tsushima Warm Current (TWC) flowing in the East China/Japan seas through the Korea-Tsushima Straits; 2: Cheju Warm Current (CWC) rounding Jeju-do clockwise eventually turning into the northern Okinawa Trough west of Kyushu, forming the Western Kyushu Current (WKC); and 3: Yellow Sea Warm Current (YSWC) flowing northward in winter monsoon from CWC at the Yellow Sea entrance west of Jeju-do.

Coastal currents on the inner shelf and the shallow part of the middle shelf in general are seasonal, with large variations in current direction and speed.  In winter they tend to flow southward along the Chinese and Korean coasts; in summer the currents are reversed in direction along the western coast of Korea and southeastern Chinese coast south of the Changjiang River mouth.  In summer less-saline water coming from the South China Sea flows through the Taiwan Strait and then spreads eastward over the western East China Sea.

Bohai Sea is a semi-enclosed and shallow bay connected on its east side with the Yellow Sea (Song et al., 2017).  The current system in Bohai Sea is mainly composed of the continuation of the YSWC from the Yellow Sea which entering the Bohai Sea through the northern part of the Bohai Strait and the outgoing Yellow Sea Coastal Current through the southern part of Bohai Strait to the Yellow Sea.  The Bohai Sea is characterized to have strong winter gales which can greatly enhance the water exchange.

The following discussion about the distribution of some calanoid species in the China seas, unless otherwise mentioned, is based on Chen, Q. (1992).

*Calanus sinicus* is a high saline and high thermal species and a major species of zooplankton in the open central waters of Bohai Sea, Yellow Sea, and East China Sea.  Its distribution extends to the north coast of South China Sea in winter, however, losing its dominancy in the zooplankton community.  The expansion and reduction of distribution of *C. sinicus* are highly related to the oceanography of the area* *(Hwang & Wong, 2005).  *C. sinicus* breeds in May/June, August, and November in the Bohai Sea and northern Yellow Sea, slightly earlier in March/April, July/August, and October in the southern Yellow Sea, in April, June/July, and October in the East China Sea, and slightly later in April/May, July/August, and January in the Taiwan Strait.  There are only two breeding seasons in the Guangdong coastal waters and the Beibu Gulf of the South China Sea.  The change in breeding seasons in different seas is apparently related to the water temperature, and therefore ocean currents.  Increase of zooplankton biomass in the China seas corresponds with breeding season of the copepods.

In the Bohai Sea, *Calanus sinicus* is common throughout the year. It is predominant in summer and fall in the central part.  In late spring to early summer its dominancy expands to the coastal waters due to the influence of the inward drifting Yellow Sea Warm Current.

In the Yellow Sea, *Calanus sinicus* is always abundant in the central open waters and is a representative species in spring, summer, and autumn.  In late spring to early summer the shoreward expansion of high saline water carries *C. sinicus* to the Shandong coastal area.  In summer and fall, owing to the expansion of the less saline coastal waters, *C. sinicus *is forced to retreat toward central part.

*Calanus sinicus* is a dominant species throughout the year in the open waters of the East China Sea.  Its distribution expands to the coastal waters from the Changjiang River mouth to Taiwan Strait in winter when Changjiang River runoff is weakened and influence of NE monsoon and the China Coastal Current is strengthened.

In winter, and extending to spring, influenced by the China Coastal Current and enforced by the NE monsoon, *Calanus sinicus* is drifted to the coastal waters of Guangdong and may be as far west as the Beibu Gulf, a gulf surrounded by Vietnam and China (three provinces: Guangxi, Guangdong and Hainan).

*Labidocera euchaeta* is, similar to *Calanus sinicus, *also recorded in all China seas.  However, it is a species of low saline waters and, different from *C. sinicus*, is more abundant in coastal waters than in open seas.  It is a dominant species in the coastal waters of northern Liaoning Peninsula and Laizhou Gulf in the Bohai Sea, and southern Liaoning Peninsula in the Yellow Sea.  Its dominance in the northern Liaoning coastal water is replaced by *C. sinicus* in late spring and early summer due to the strengthening Yellow Sea Warm Current.  In the East China Sea, *L. euchaeta* is a dominant species in the coastal waters, especially a year round dominant species in the Changjiang River mouth.  In the South China Sea it is abundant in the coastal waters of Guangdong Province.

*Euchaeta concinna* is a tropical species and spreads over South China Sea, Taiwan Strait, and East China Sea.  Less frequently it expands to the southern Yellow Sea by the influence of Yellow Sea Warm Current.  In the South China Sea, it is a major component of the subsurface zooplankton community, and abundant in the northern South China Sea where oceanic and coastal waters mix.  It is a dominant species on the west coast of Taiwan Strait in summer but is forced to bottom water when the Kuroshio Branch Current sinks in the area west of Taiwan in winter.

*Subeucalanus subcrassus* is a tropical species and present in both oceanic and coastal waters from the South China Sea to East China Sea, and, to a less extent, the southern Yellow Sea due to the influence of northward drifting Yellow Sea Warm Current in fall and winter.  In the South China Sea, *S. subcrassus* has been recorded from open waters in central South China Sea to near shore waters south of Guangdong Province and as well as in the Beibu Gulf and Thailand Gulf.  From the northeastern South China Sea northward, *S. subcrassus* is abundant in the Taiwan Strait, especially in summer, and widely distributed and dominant in fall in the East China Sea.  It is also fairly abundant in the in the Ilan Bay, east of Taiwan (Lee et al. 2009).

The composition of calanoid copepods in the China seas is strongly influenced by the Kuroshio.  Grice (1962) studied the copepods of the equatorial Pacific.  He recorded 109 species of calanoid copepods in his survey.  All but four (*Aetideus pacificus, Pleuromamma indica, Parvocalanus dubia* and *Scopalatum smithae*) of the species reported by him also occur in the China seas.  There may have more species that are common in the equatorial Pacific and the China seas if more collections from the equatorial water are available for study.  This is a clear indication that the Kuroshio, due to its upstream the North Pacific Equitorial Current, is an important contributor to the composition of calanoid copepods in the China seas.
