
# **REFERENCES**

Andronov, V.N., 1974.  Phylogenetic relationships of the large taxa within the suborder Calanoida (Crustacea, Copepoda).  Zoologicheskii Zhurnal 53: 1002-1012. (in Russian with English summary) (English translation is available from the U.S. Department of Commerce and the National Science Foundation, Washington D.C. by the Al-Ahram Center for Scientific Translations.)

Andronov, V.N.,1991.  On renaming of some taxa in Calanoida (Copepoda).  Zoologicheskii Zhurnal 70 (6): 133-134.  (In Russian with English Summary)

Boxshall, G.A. & S.H. Halsey, 2004.  An Introduction to Copepod Diversity.  Parts I and II.  Ray Society, 166: 966 pp.

Bradford, J. M., L. Haakonssen & J. B. Jillett, 1983.  The marine fauna of New Zealand: Pelagic copepods: Families Euchaetidae, Phaennidae, Scolecithricidae, Diaixidae, and Tharybidae.  New Zealand Oceanographic Institute Memoir, 90: 7-150.

Bradford, J. M. & J. B. Jillett, 1980.  The marine fauna of New Zealand: pelagic calanoid copepods: family Aetideidae.  New Zealand Oceanographic Institute Memoir, 86: 5-102.

Bradford-Grieve, J. M., 1994.  The marine fauna of New Zealand: Pelagic copepods: Families Megacalanidae, Calanidae, Paracalanidae, Mecynoceridae, Eucalanidae, Spinocalanidae, Clausocalanidae.  New Zealand Oceanographic Institute Memoir, 102: 1-160.

Bradford-Grieve, J. M., 1999.  The marine fauna of New Zealand: Pelagic copepods: Families Bathypontiidae, Arietellidae, Augaptilidae, Heterorhabdidae, Lucicutiidae, Metridinidae, Phyllopodidae, Centropagidae, Pseudodiaptomidae, Temoridae, Candaciidae, Pontellidae, Sulcanidae, Acartiidae, Tortanidae.  NIWA Biodiversity Memoir, 111: 1-268

Bradford-Grieve, J. M., L. Markhaseva, C. E. F. Rocha & B. Abiyahi, 1999.  Copepoda.  In: Boltovskoy, D. (ed.), South Atlantic Zooplankton, 2: 869-1098.

Breemen, P. J. van, 1908.  VIII. Copepoden, Nordisches Plankton, Zoologischer Teil 4(8): 1-264.(In German)

Brodsky, K. A., 1950.  Calanoida of the Far Eastern Seas and Polar Basin of the USSR.  Keys to the Fauna of the USSR, the Zoological Institute of the Academy of Sciences of the USSR, No. 35.  (Israel Program for Scientific Translations, 1st edition, 1967, 440 pp.)

Campos Hernández, A & E. Suárez Morales, 1994.  Copépodos pelágicos del Golfo de Mexico y Mar Caribe.  I. Biología y Sistematica, i-vii, 1-360. (In Spanish)

Chang, W.-B., H.-U. Dahms & L.-C. Tseng, 2010.  Copepods assemblages in an enbayment of Taiwan during monsoonal transitions. Zoological Studies, 49: 735-748.

Chen, B.-Y., 1984.  Preliminary study on the distribution system of marine copepods in the China seas.  Acta Oceanologica Sinica, 5, suppl.: 914-922. (In Chinese with English abstract)

Chen, H. & G. Liu, 2015.  Zooplankton community structure in the Yellow Sea and East China Sea in autumn.  Brazilian Journal of Oceanography, 63: 455-468.

Chen, H., G. Liu, Y. Zhu, Q. Jiang, 2015.  Spatial and temporal variations of pelagic copepods in the north Yellow Sea.  Journal of Ocean University of China (Oceanlic and Coastal Sea Research), 14: 989-998. (In Chinese)

Chen, Q.-C. 1982.  The marine zooplankton of Hong Kong.  Proceedings of the First International Marine Biological Workshop: The Marine Flora and Fauna of Hong Kong and Southern China, pp. 789-799.

Chen, Q,-C., 1986.  Studies on marine copepods by Chinese scientists during the last 35 years.  Syllogeus, 58: 524-529.

Chen, Q.-C., 1992.  Zooplankton of China Seas (1). Science Press, Beijing, New York, iii + 87 pp. 

Chen, Q.-C., 2008.  Copepoda.  *In*: Checklist of Marine Biota of China Seas (R. Liu, ed.), pp. 608-635.  Science Press, Beijing, China. (In Chinese)

Chen, Q.-C. & C.-J. Shen, 1974.  The pelagic copepods of the South China Sea II.  Studia Marina Sinica, 9: 125-137. (In Chinese with English abstract)

Chen, Q.-C., C.K. Wong, P.F. Tam, C.N.W. Lee, J.Q. Yin, L.M. Huang & Y.H. Tam, 2003.  Variations in the abundance and structure of the planktonic copepod community in the Pearl River estuary, China.  Proceedings of an International Workshop Reunion Conference, Hong Kong 21-26 October 2001, Morton, B. (ed.), Hong Kong University Press, pp. 389-400.

Chen, Q.-C., G.-X. Zhang, & J.-Q. Yun, 1987.  Species, quantity and biology of zooplankton.  *In*: Zengmu Ansha - Reports on the Comprehensive Investigations of the Southern Territory of China.  Zao, X & B. Lee (eds.), Science Press, Beijing, pp.132-146. (In Chinese)

Chen, Q.-C. & S.-Z. Zhang, 1965.  The planktonic copepods of the Yellow Sea and the East China Sea I. Calanoida.  Studia Marina Sinica, 7: 20-131. (In Chinese with English abstract)

Chen, Q.-C. & S.-Z. Zhang, 1974.  The pelagic copepods of the South China Sea I.  Studia Marina Sinica 9: 101-116. (In Chinese with Chinese abstract)

Chen, R. S., Z. C. Zhou, S. Q. Chen, & J. S. Jiang, 1988.  Zooplankton.  *In*: Report of the Comprehensive Investigations on Environmental Resources in the Central Part of the South China Sea (National Bureau of Oceanology, ed.), pp. 230-251.  Science Press, Beijing, China. (In Chinese)

Chihara, M. & M. Murano, 1997.  An Illustrated Guide to Marine Plankton of Japan.  Tokai University Press, xxxvi+1574pp.  (Calanoida: 660-931.  Acartiidae by H. Ueda, pp. 669-680; Aetideidae by S. Nishida, pp. 681-718; Arietellidae by S. Ohtsuka, pp. 719-726; Augaptilidae by S. Nishida, pp. 727-736; Calanidae by H. Toda, pp. 937-948; Calocalanidae by H. Ueda, pp. 749-751; Candaciidae by S. Ohtsuka, 752-764; Centropagidae by S. Ohtsuka, pp. 765-774; Clausocalanidae by H. Ueda, pp. 775-786; Eucalanidae by H. Toda, pp. 787-796; Euchaetidae by S. Ohtsuka, pp. 797-815; Heterorhabdidae by S. Ohtsuka, pp. 816-828; Lucicutiidae by H. Hatori, pp. 829-832; Mecynoceridae by H. Ueda, p. 833; Megacalanidae by S. Nishida, pp. 834-836; Metridinidae by H. Hatori, pp. 837-843; Paracalanidae by H. Ueda, pp. 844-851; Phaennidae by H. Toda, pp. 852-861; Phyllopodidae by S. Ohtsuka, pp. 862-864; Pontellidae by S. Ohtsuka, pp. 865-890; Pseudocyclopidae by S. Ohtsuka, p. 891; Pseudocyclopiidae by S. Ohtsuka, p. 892; Pseaudodiaptomidae by Mirakawa, pp. 893-897; Ryocalanidae by S. Ohtsuka, p. 898; Scolecitrichidae by S. Nishida, pp. 899-912; Stephidae by S. Ohtsuka, pp. 913-915; Temoridae by H. Itoh, pp. 916-919; Tharybidae by S. Nishida, pp.920-923; Tortanidae by S. Ohtsuka, pp. 924-931).(In Japanese)

Dahm, H.-U., Tseng et al,, 2012. Biodiversity of planktonic copepods in the Lanyang River (northeastern Taiwan), a typical watershed of Oceania.  Zoological Studies, 51: 160-174.

Dai, Y. J. Lin, M. Lin, L. Chen, & Y. Huang., 1991.  An ecological study of the zooplankton in western Xiamen Harbour, China.  Asian Marine Biology, 8: 45-56.

Dana, J.D. 1846.  Notice of some genera of Cyclopacea.  Annals and Magazine of Natural History 18: 181-185; American Journal of Science (2) 1: 225-230.

Dur, G., J.-S. Hwang, S. Souissi, L.-C. Tseng, C.-H. Wu & S.-H. Hsiao, 2007.  An overview of the influence of hydrodynamics on the spatial and temporal patterns of calanoid copepod communities around Taiwan.  Journal of Plankton Research, 29: 997-1116.

Esterly, C. O., 1905.  The pelagic Copepoda of the San Diego region.  University of California Publications in Zoology, 2 (4): 113-233, figs. 1-62.

Esterly, C. O., 1906.  Addition to the copepod fauna of the San Diego region.  University of California Publications in Zoology, 3 (5): 53-92, pls. 9-14.

Esterly, C. O., 1911.  Third report on the Copepoda of the San Diego region.  University of California Publications in Zoology, 6(14): 313-352, pls. 26-32.

Esterly, C. O. 1913.  Fourth taxonomic report of the Copepoda of the San Diego region.  University of California Publications in Zoology, 11 (10): 181-196, pls. 10-12.

Fang, W., Z. Guo & Y. Huang, 1998.  Observational study of the circulation in the southern South China Sea.  Chinese Science Bulletin, 43: 898-905.

Gardner, G. A. & I. Szabo, 1982.  British Columbia pelagic marine Copepoda: An Identification manual and annotated bibliography.  Canadian Special Publication of Fisheries and Aquatic Science, 62: 1-536.

Giesbrecht, W.  1882.  Die freilebenden Copepoden der Kieler Föhrde.  VI. Bericht Commission zur wissenschaftlichen Untersucheng der Deutschen Meere in Kiel, für 1877-1881, Abt. 1: 87-168, pls. 1-12. (In Germen)

Giesbrecht, W.  1893. Systematik und Faunistik der pelagischen Copepoden des Golfes von Neapel und der angrenzenden Meeres-Abschnitte.  Fauna und Flora des Golfes von Neapel 19: i-ix, 1-831, pls. 1-54.(In Germen)

Greenwood, J. G., 1976.  Calanoid copepods of Moreton Bay (Queensland) I. Families Calanidae, Eucalanidae, and Paracalanidae.  Proceedings of the Royal Society of Queensland, 87: 1-28.

Greenwood, J. G., 1977.  Calanoid copepods of Moreton Bay (Queensland) II. Families Calocalanidae and Centropagidae.  Proceedings of the Royal Society of Queensland, 88: 49-67.

Greenwood, J. G., 1978.  Calanoid copepods of Moreton Bay (Queensland) III. Families Temoridae to Tortanidae, excluding Pontellidae.  Proceedings of the Royal Society of Queensland, 89: 1-21.

Greenwood, J. G., 1979.  Calanoid copepods of Moreton Bay (Queensland) IV. Family Pontellidae.  Proceedings of Royal Society of Queensland, 90: 93-111.

Greenwood, J. G., 1982.  Calanoid copepods of Moreton Bay (Queensland) V. Ecology of the dominant species.  Royal Society of the Royal Society of Queensland, 93: 49-64.

Grice, D. G., 1962.  Calanoid copepods from equatorial waters of the Pacific Ocean.  Fisheries Bulletin, 61:171-245.

Harding, G., 2004.  Key to the adult pelagic calanoid copepods found over the continental shelf of the Canadian Atlantic coast.  Marine Environmental Science, Bedford Institute of Oceanography, Dartmouth, Canada, 68pp.

He, D. & G. Yang, 1990.  Distribution of the pelagic copepods in Kuroshio upstream area and adjacent waters in spring, 1986.  1. Horizontal distribution.  *In*: Selected Papers on Kuroshio Investigation (J. L. Su ed.), pp. 249-265.  Science Press, Beijing, China.  (In Chinese with English abstract)

Hsiao, S. H., T.-S. Fang, C.-t. Shih & J. S. Hwang, 2011.  Effects of the Kuroshio Current on copepod assemblages in Taiwan.  Zoological Studies, 50: 475-490.

Hsiao, S. H., S. Ka, T.-S. Fang & J. S. Hwang, 2011.  Zooplankton assemblages as indicators of seasonal changes in water masses in the boundary waters between the East China Sea and the Taiwan Strait.  Hydrobiologia, 666: 317-330.

Hsiao, S. H., C. Y. Lee, C.-t. Shih & J. S. Hwang, 2004.  Calanoid copepods of the Kuroshio Current east of Taiwan with notes on the presence of *Calanus jashnovi *Hulsemann, 1994.  Zoological Studies, 43: 323-331.

Hsieh, C.-h., C.-S. Chen & T.-S. Chiu, 2005.  Composition and abundance of copepods and ichthyoplankton in Taiwan Strait (western North Pacific) are influenced by seasonal monsoons.  Marine & Freshwater Research, 56: 153-161.

Hsieh, C.-H. & T.-S. Chiu, 2002.  Summer spatial distribution of copepods and fish larvae in relation to hydrography in the northern Taiwan Strait.  Zoological Studies, 41: 85-98.

Hsieh, C.-H., T.-S. Chiu, & C.-t. Shih, 2004.  Copepod diversity and composition as indicators of intrusion of the Kuroshio Branch Current into the northern Taiwan Strait in spring 2000.  Zoological Studies, 43: 393-403.

Hsu, P. K., W. Z. Lo & C.-t. Shih, 2008.  The coupling of copepod assemblages and hydrography in a eutrophic lagoon in Taiwan: Seasonal and spatial variations.  Zoological Studies, 47: 172-184.

Hu, J. Y., H. Kawamura, H. Hong & Y. Qi, 2000. A review on the currents in the South China Sea: Seasonal circulation, South China Sea Warm Current and Kuroshio Intrusion.  Journal of Oceanography, 56: 607-624.

Hu, J. Y. & M. S. Liu, 1992.  The current structure during summer in southern Taiwan Strait.  Tropic Oceanology, 11(4): 42-47. (In Chinese with English abstract)

Huang, J. & B. Chen, 1985.  Species composition and distribution of planktonic copepods in the Jiulong Jiang estuary, Fujian.  Taiwan Strait 3: 79-88. (In Chinese with English abstract)

Huang, J. Q., S. Q. Li & H. B. Ho, 2000.  Community characteristics of planktonic copepods in Luoyuan Bay, Fujian.  Marine Sciences, 24: 1-4. (in Chinese with English abstract)

Huys, R. and G.A. Boxshall, 1991.  Copepod Evolution.  Ray Society, 159: 468 pp.

Hwang, J. S., Q.-C. Chen, W.-Z. Lo, M.-P. Chen, 2000.  Taxonomic composition and abundance of the copepods in the northeastern South China Sea.  National Taiwan Museum Special Publications Series, 10: 101-108.

Hwang, J. S., Q. C. Chen & C. K. Wong, 2003.  Taxonomic composition, density and biomass of free-living copepods in the coastal waters of southwestern Taiwan.  Crustaceans, 76: 193-206.

Hwang, J.-S., H.-U. Dahms, L.-C. Tseng, & Q.-C. Chen. 2007.  Intrusions of the Kuroshio Current in the northern South China Sea affect copepod assemblages of the Luzon Strait.  Journal of Experimental Marine Biology and Ecology, 352: 12-27.

Hwang, J.-S., R. Kumar, C.-W. Hsieh, A.-Y. Kuo, S. Souissi, M.-H. Hsu, J.-T. Wu, W.-C. Liu, C.-F. Wang & Q.-C. Chen, 2010.  Patterns of zooplankton distribution along the marine, estuarine, and riverine portions of the Danshuei ecosystem in northern Taiwan.  Zoological Studies, 49: 335-352.

Hwang, J.-S., S. Soussi, H. U. Dahms, L.-C. Tseng, F. G. Schmidt, Q.-C. Chen, 2009.  Rank-abundance allocations as a tool to analyze planktonic copepod assemblages off the Danshuei River estuary (northern Taiwan).  Zoological Studies, 48: 49-62.

Hwang, J.-S., S. Soussi, L.-C. Tseng, L. Seuront, F. G. Schmidt, L.-S. Fang, S. S. Peng, C.-H. Wu, S.-H. Hsiao, W-H. Twan, T.-P. Wei, R. Kumar, T.-H. Fang, Q.-C. Chen, C.-K. Wong, 2006.  A 5-year study of the influence of the northeast and southwest monsoons on copepod assemblages in the boundary coastal waters between the East China Sea and the Taiwan Strait.  Journal of Plankaton Research, 28: 943-958.

Hwang, J.-S., Y. Y. Tu, L.-C. Tseng, L.-S. Fang, S. Souissi, T.-H. Fang, W.-T. Lo, W.-H. Twan, S.-H. Hsiao, C.-H. Wu, S.-H. Peng, T.-P. Wei & Q.-C. Chen, 2004.  Taxonomic composition and seasonal distribution of copepod assemblages from waters adjacent to nuclear power plant I and II in northern Taiwan.  Journal of Marine Science & Technology, 12: 380-391.

Hwang, J.-S. and C. K. Wong, 2005. The China Coastal Current as a driving force for transporting *Calanus sinicus* (Copepoda: Calanoida) from population centers to waters off Taiwan and Hong Kong during the winter northeast monsoon period.  Journal of Plankton Research, 27: 205-210.

Jan, S., J. Wang, C.-S. Chern & S.-Y. Chao, 2002.  Seasonal variation of the circulation in the Taiwan Strait.  Journal of Marine System, 35: 249-268.

Jin, H.-w., H.-x. Xu, W.-d. Wang, G.-l. Pan & B.-c. Yu, 2009.  Distribution features of zooplankton in the Zhejiang coastal waters.  Journal of Marine Sciences, 27: 55-62.

Ka, S. & J.-S. Hwang, 2011.  Mesozooplankton distribution and composition on the northeastern coast of Taiwan during autumn: Effects of the Kuroshio Current and hydrothermal vents.  Zoological Studies, 50: 155-163.

Lan, Y.-C, M.-A. Lee, W.-Y. Chen, F.-J. Hsieh, J.-Y. Pan, D.-C. Liu, W.-C. Su, 2008a.  Seasonal relationships between the copepod community and hydrographic conditions in the southern East China Sea.  ICES Journal of Marine Science, 65: 462-458.

Lan, Y.-C., M.-A. Lee, C.-H. Liao, W.-Y. Chen, D.-A. Lee, D.-C. Liu, & W.-C. Su, 2008b.  Copepod community changes in the southern East China Sea between the early and late northeasterly monsoon.  Zoological Studies, 47: 61-74.

Lan, Y.-C., M.-A. Lee, C.-H. Liao & K.-T. Lee, 2009.  Copepod community structure of the winter frontal zone induced by the Kuroshio Branch Current and the China Coastal Current in the Taiwan Strait.  Journal of Marine Science & Technology, 17: 1-6.

Lan, Y.-C., C.-t. Shih, M.-A. Lee & H.-Z. Shieh, 2004.  Spring distribution of copepods in relation to water masses in the northern Taiwan Strait.  Zoological Studies, 43: 332-343.

Lee, C. N. W., 2003.  Seasonal changes in the planktonic copepod community of the southeastern coastal waters of Hong Kong.  *In*: Proceedings of an International Workshop Reunion Conference, Hong Kong 21-26 October 2001, T. Morton (ed.), Hong Kong University Press, Hong Kong, pp. 367-387.

Lee, C. N. W. & Q.-C. Chen, 2003.  A historical and biogeographical analysis of the marine planktonic copepod community in Hong Kong: a record of change.  Proceedings of an International Workshop Reunion Conference, Hong Kong 21-26 October 2001, Morton, B. (ed.).  Hong Kong University Press, Hong Kong, pp. 433-457.

Lee, C.-Y., D.-C. Liu, & W.-C. Su, 2009.  Seasonal and spatial variations in the planktonic copepod community of Ilan Bay and adjacent Kuroshio waters off northeastern Taiwan.  Zoological Studies, 48: 151-161.

Lee, C.-Y., C.-t. Shih & C. C. Hsu, 2006.  Community structure of planktonic copepods in I-Lan Bay and the adjacent Kuroshio waters off northeastern Taiwan.  Crustaceana, 79: 1223-1240.

Li, K. Z., X. J. Wu, Y. H. Tan, H. Huang, J. D. Dong, & L. M. Huang, 2016.  Spatial and temporal variability of copepod assemblages in Sanya Bay, northern South China Sea.  Regional Studies in Marine Science, 7: 168-176.

Li, S. & J. Huang, 1984.  On two new species of planktonic Copepoda from the estuary of Jiulong River, Fujian, China.  Journal of Xiamen University (Natural Science), 23: 380-390. (In Chinese with English abstract)

Lian, G. S. & J. M. Lin, 1978.  Studies on the calanoid copepods of the south Yellow Sea and the East China Sea.  Oceanic Science and Technology, 11 (10): 59-112. (In Chinese with English abstract)

Lian, G. S. & J. M. Lin, 1983.  On the taxonomy of the pelagic copepods in the south Yellow Sea and the East China Sea.  Collected Oceanic Works, 6: 127-148. (In Chinese with English abstract)

Lian, G. S. & J. M. Lin, 2008.  Copepoda.  *In*: Marine Species and Their Distribution in China’s Seas, 2nd Edition.  Z.-g. Huang (ed.), China Ocean Press, Beijing, pp. 549-577. (In Chinese).

Lian, G., Y. Wang, R. Sun, J. Hwang, 2018.  Species Diversity of Marine Planktonic Copepods in China’s seas, volume 1. China Ocean Paress, Beijing, 647 pp.

Liao, C.-H., W.-J Chang, M.-A. Lee & K.-T. Lee, 2006.  Summer distribution and diversity of copepods in upwelling waters of the southeastern East China Sea.  Zoological Studies, 45: 378-394.

Lie, H.-J. & C.-H. Cho, 2016.  Seasonal circulation patterns of the Yellow and East China seas derived from satellite-tracked drifter trajectories and hydrographic observations.  Progress in Oceanography, 146: 121-141.

Lin, D., X. Q. Li, H. D. Fang, Z. H. Dong, Z. X. Huang & J. H. Chen, 2011.  Calanoid copepods assemblages in Pearl River estuary of China in summer: Relationships between species distribution and environmental variables.  Estuarine, Coastal and Shelf Science, 93: 259-267.

Lin, J.-h., 2007.  Ecological characteristics on macro-medium planktonic copepods in the subtropical circulation zone east of Taiwan Island.  Acta Oceanologica Sinica, 29: 92-97. (In Chinese with English abstract)

Lin, Y. & G. Lian, 1988.  Ecology of planktonic copepods in the Taiwan Strait.  Taiwan Strait, 7: 248-255. (In Chinese with English abstract)

Lin, Y. & Y. Nakamura, 1992.  Distribution of planktonic copepods in the Kuroshio of the East China Sea southwest off Kyushu, Japan.  Acta Oceanologica Sinica, 2: 91-98. (In Chinese)

Lo, W.-T., H.-U. Dahms & J.-S. Hwang, 2014.  Water mass transport through the northern Bashi Channel in the northeastern South China Sea affects copepod assemblages of the Luzon Strait.  Zoological Studies, 53:66..

Lo, W. T., J. S. Hwang & Q. C. Chen, 2001.  Identity and abundance of surface-dwelling, coastal copepods of southwestern Taiwan.  Crustaceana, 74: 1139-1157.

Lo, W.-T., J.-S. Hwang & Q. C. Chen, 2004.  Spatial distribution of copepods in surface waters of the southwestern Taiwan Strait.  Zoological	Studies, 43: 218-228.

Lo, W.-T., C.-t. Shih & J.-S. Hwang, 2004.  Diel vertical migration of the planktonic copepods at an upwelling station north of Taiwan, western North Pacific.  Journal of Plankton Research, 26: 89-97.

Luo, X., J. Zeng, X. Xu, Y. Liao, & J. Liu, 2016.  Distribution of zooplankton in the Zhoushan Sea and its relationship with environmental factors in summer and autumn.  Acta Ecologica Sinica, 36: 8194-8204. (In Chinese with English abstract)

Meng, F., F.-P. Huang, Q.-L. Li & Z.-D. Ma, 1990.  Zooplankton in the Kuroshio region of the East China Sea in the summer of 1987. [In Chinese with English summary]  *In*: Selected Research Papers on Kuroshio Investigation, J. L. Su (ed.), Science Press, Beijing, 2: 92-98. (In Chinese with English abstract)

Meng, F., F.-P. Huang, Z.-D. Ma & F.-P. Li, 1991.  On the composition and distribution of zooplankton species in the Kuroshio region in the north of East China Sea. [In Chinese with English summary]  *In*: Selected Research Papers on Kuroshio Investigation, J. L. Su (ed.), Science Press, Beijing, 3: 150-160. (In Chinese with English abstract)

Meng, F., F.-P. Huang, Z.-D. Ma & F.-P. Li, 1993.  A preliminary report of zooplankton in the Kuroshio and adjacent waters [In Chinese with English summary]  *In*: Selected Research Papers on Kuroshio Investigation, J. L. Su (ed.), Science Press, Beijing, 1: 97-105. (In Chinese with English abstract)

Meng, F., J. Zhao, Q.-L. Li & Z.-D. Ma, 1992.  The ecological structure of the zooplankton in the Kuroshio frontal eddy in the northern East China Sea. [In Chinese with English summary]  *In*: Selected Research Papers on Kuroshio Investigation, J. L. Su (ed.), Science Press, Beijing, 4: 142-150. (In Chinese with English abstract)

Mori, T., 1937.  The Pelagic Copepoda from the Neighbouring Waters of Japan.  Privately published, 150pp, 80 pls.

Mulyadi, 2004.  The Pelagic Calalnoid Copepods of the Families Acartiidae, Aetideidae, Augaptilidae, Calanidae, Calocalanidae, Candaciidae, Centropagidae, Clausocalanidae, Eucalanidae, Euchaetidae, Heterorhabdidae, Metridinidae, Paracalanidae, Phaennidae, Pseudodiaptomidae, Scolecitrichidae, and Tortanidae in Indonesian Waters.  *Research Center for Biology, Indonesia Institute of Sciences, Bogor*, 195 pp.

Owre, H. B. & M. Foyo, 1967.  Copepods of the Florida Current.  Fauna Caribaea 1.  Copepoda, 1-137.

Palomares, R., E. Suárez & S. Herández-Trujillo, 1998.  Catálogo delos Copépodos (Crustacea) Pelágicos del Pacífico Mexicano.  Centro Interdisciplinaria de Ciencias Marinas (CICIMAR-IPN), El Colegio de la Frontera Sur (ECOSUR), Mexico City, 352pp. (In Spanish)

Qiu, B., D. L. Rudnick, I. Cerovecki, B. D. Cornuelle, S. Chen, M. C. Schönau, J. L. McClean & G. Gopalakrishnan, 2015.  The Pacific North Equatorial Current. New insights from the origins of the Kuroshio and Mindanao Currents (OKMC) Project.  Oceanography, 28 (4): 24-33.

Razouls, C., F. de Bovée, J. Kouwenberg & N. Desreumaux, 2005-2917.  Diversity and Geographic Distribution of Marine Planktonic Copepods, available at *[http://copepodes.obs-banyuls.fr/en](http://copepodes.obs-banyuls.fr/en)*. (In French)

Rose, M., 1933.  Faune de France.  26: 1-374. (In French)

Rose, M., 1955.  Quelques notes sur le plancton marine recuelli en 1953 par M. G. Ranson, dans la baie de Nhatrang-Cauda.  Bulletin du Museum, ser.2, 17: 387-393. (In French)

Rose, M., 1956.  Les copepodes pelagiques de la baie de Cauda (Viet-Nam).  28: 458-465. (In French)

Sars, G. O., 1901.  An account of of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Calanidae, Eucalanidae, Paracalanidae, Pseudocalanidae, Aetideidae (part)) 4: 1-28, pls 1-16.

Sars, G. O., 1902a.  An account of of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Aetideidae (concluded), Euchaetidae,  Phaennidae) 4: 29-48, pls. 17-32.

Sars, G. O., 1902b.  An account of of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Scolecithricidae, Diaixidae, Stephidae, Tharybidae) 4: 49-72, pls. 33-48.

Sars, G. O., 1902c.  An account of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Centropagidae, Diaptomidae) 4: 73-96, pls. 49-64.

Sars, G. O., 1902d.  An account of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Temoridae, Metridiidae, Heterorhabdidae (part)) 4: 97-120, pls. 65-80.

Sars, G. O., 1902d.  An account of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Heterorhabdidae (continued), Arietellidae, Pseudocyclopidae, Candaciidae, Pontellidae) 4: 121-144, pls. 81-96

Sars, G. O., 1903.  An account of of the Crustacea of Norway with short descriptions and figures of all the species.  Copepoda Calanoida (Parapontellidae, Acartiidae, Supplement) 4: 145-172, pls. 97-102, suppl. pls. 1-6.

Sars, G. O., 1925 (plates, 1924).  Copepodes particulierement bathypelagiques provenant des Campagnes scientifiques du Prince Albert 1er de Monaco.  Resultats des Campagnes scientifiques accomplies sur son Yacht par Albert 1er Prince Souverain de Monaco, 69: 1-408, pls. 1-127. (In French)

Scott, A., 1909.  The Copepoda of the Siboga Expedition.  29: 1-323.

Sewell, R.B.S., 1929.  The Copepoda of Indian Seas.  Memoires of the Indian Museum, 10: 1-220.

Sewell, R.B.S., 1932.  The Copepoda of Indian Seas.  Memoires of the Indian Museum, 10: 221-407.

Sewell, R.B.S., 1947.  The free-swimming planktonic Copepoda.  Scientific Reports of the John Murray Expedition, 1933-34, Zoology, 8: 1-303.

Shen, C.-j. & S.-o. Bai, 1956.  The marine Copepoda from the spawning ground of *Pneumatophores japonicus* ( Houttuyn ) off Chefoo, China.  Acta Zoologica Sinica, 8: 177-234. (In Chinese with English abstract)

Shen, C.-j. & F.-s. Lee, 1963.  The estuarine Copepoda of Chiekong and Zaikong rivers, Kwangtung Province, China.  Acta Zoologica Sinica, 15: 571-596. (In Chinese with English abstract)

Shih, C.-t. & T. S. Chiu, 1998.  Copepod diversity in the water masses of the southern East China Sea north of Taiwan.  Journal of Marine Systems, 15: 533-542.

Shih, C.-t. & S.-S. Young, 1995.  A checklist of free-living copepods, including those associated with invertebrates, reported from the adjacent seas of Taiwan.  Acta Zoologica Taiwanica, 6(2): 65-81.

Song, J., J. Guo, J. Li, L. Mu, Y. Liu, G. Wang, Y. Li & L. I. Huan, 2017.  Definition of water exchange zone between the Bohai Sea and Yellow Sea and the effect of winter gale on it.  Acta Oceanolgica Sinica, 36: 17-25.

Song, X., A. Liu, Y. Ma, G. Sun & L. Liu, 2010.  Study on the plankton community in the sea area of Dongying in dry season.  Transactions of Oceanology and Limnology, 1: 95-102.

Tan, T.-H., 1969.  A list of pelagic Copepoda from the surrounding waters of Taiwan ( with a key to genera ).  Report of The Institute of Fishery Biology of Ministry of Economic Affairs and National Taiwan University, 2(3): 45-55.

Tan, T.-H., 1971. Tseng, Souissi et al., 2008;  On distribution of biomass and abundance of zooplankton in waters surrounding Taiwan.  Acta Oceanologica Taiwanica, 1: 127-136.

Tan, Y., L., Huang, Q. Chen & S. Huang, 2004.  Seasonal variation in zooplankton composition and grazing impact on phytoplankton standing stock in the Pearl River estuary, China.  Continental Shelf Research, 24: 1949-1968.

Tanaka, O., 1956a.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  I. Families Calanidae and Eucalanidae.  Publications of the Seto Marine Biological Laboratory, 5: 251-272.

Tanaka, O., 1956b.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  II. Families Paracalanidae and Pseudocalanidae.  Publications of the Seto Marine Biological Laboratory, 5: 364-406.

Tanaka, O., 1957a.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  III. Families Aetideidae (Part 1).  Publications of the Seto Marine Biological Laboratory, 6: 31-68.

Tanaka, O., 1957b.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  IV. Families Aetideidae (Part 2).  Publications of the Seto Marine Biological Laboratory, 6: 169-207.

Tanaka, O., 1958.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  V. Family Euchaetidae.  Publications of the Seto Marine Biological Laboratory, 6: 327-367.

Tanaka, O., 1960a.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  VI. Family Phaennidae and Tharybidae.  Publications of the Seto Marine Biological Laboratory, 8: 85-135.

Tanaka, O., 1960b.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  VII. Family Scolecithricidae (Part 1).  Publications of the Seto Marine Biological Laboratory, 9: 139-190.

Tanaka, O., 1962.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  VIII. Family Scolecithricidae (Part 2).  Publications of the Seto Marine Biological Laboratory, 10: 35-90.

Tanaka, O., 1963.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  IX. Family Centropagidae, Pseudodiaptomidae, Temoridae, Metridiidae and Lucicutiidae.  Publications of the Seto Marine Biological Laboratory, 11: 7-55.

Tanaka, O., 1964a.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  X. Family Heterorhabidae.  Publications of the Seto Marine Biological Laboratory, 12: 1-37.

Tanaka, O., 1964b.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  XI. Family Augaptilidae.  Publications of the Seto Marine Biological Laboratory, 12: 39-91.

Tanaka, O., 1964c.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  XII. Family Arietellidae, Pseudocyclopidae, Candaciidae, Pontellidae.  Publications of the Seto Marine Biological Laboratory, 12: 231-271.

Tanaka, O., 1965.  The pelagic copepods of the Izu region, middle Japan.  Systematic account.  XIII. Family Parapontellidae, Acartiidae, Tortanidae.  Publications of the Seto Marine Biological Laboratory, 12: 379-408.

Tanaka, O. & M. Omori, 1968.  Additional report on calanoid copepods from the Izu region. Part 1. *Euchaeta* and *Pareuchaeta*.  Publications of the Seto Marine Biological Laboratory, 16: 219-261.

Tanaka, O. & M. Omori, 1969.  Additional report on calanoid copepods from the Izu region. Part 2. *Euchiriella* and *Pseudochiriella*.  Publications of the Seto Marine Biological Laboratory, 17: 155-169.

Tanaka, O. & M. Omori, 1969.  Additional report on calanoid copepods from the Izu region. Part 3A. *Euaetideus*, *Aetideopsis*, *Chridius*, *Gaidius*, and *Gaetanus*.  Publications of the Seto Marine Biological Laboratory, 18: 109-141.

Tanaka, O. & M. Omori, 1970.  Additional report on calanoid copepods from the Izu region. Part 3B. *Chirundina*, *Undeuchaeta*, *Pseudeuchaeta*, *Valdiviella*, and *Chiridiella*.  Publications of the Seto Marine Biological Laboratory, 18: 	143-155.

Tanaka, O. & M. Omori, 1971.  Additional report on calanoid copepods from the Izu region. Part 4. *Haloptilus, Augaptilus, Centraugaptilus, Pseudaugaptilus,* and* Pachyptilus*.  Publications of the Seto Marine Biological Laboratory, 19: 249-268.

Tanaka, O. & M. Omori, 1974.  Additional report on calanoid copepods from the Izu region. Part 5. *Euaugaptilus*.  Publications of the Seto Marine Biological Laboratory, 21: 193-267.

Tanaka, O. & M. Omori, 1992.  Additional report on calanoid copepods from the Izu region. Part 6. Phaennidae.  Publications of the Seto Marine Biological Laboratory, 35: 253-271.

Tseng, L. C., H.-U. Dahms, Q.-C. Chen & J.–S. Hwang, 2008.  Copepod assemblages of the northern South China Sea.  Crustaceana, 81: 1-22.

Tseng, L. C., H.-U. Dahms, Q.-C. Chen & J.–S. Hwang, 2012.  Mesozooplankton and copepod community structures in the southern East China Sea: the status during the monsoonal transition period in September.  Helgoland Marine Research, 66: 621-634.

Tseng, L.-C., J.-J. Hung, Q.-C. Chen & J.-S. Hwang, 2013.  Seasonality of the copepod assemblage associated with interplay waters off northeastern Taiwan.  Helgoland Marine Science, 67: 507-520.

Tseng, L.-C., R. Kumar, H.-U. Dahms, C.-T. Chen, S. Soussi, Q.-C. Chen & J.-S. Hwang, 2008a.  Copepod community structure over a marine outfall area in the north-eastern South China Sea.  Journal of the Marine Biological Association of the United Kingdom, 88: 955-966.

Tseng, L.-C., R. Kumar, H.-U. Dahms, Q.-C. Chen & J.-S. Hwang, 2008b.  Monsoon-driven succession of copepod assemblages in coastal waters of the northeastern Taiwan Strait.  Zoological Studies, 47: 46-60.

Tseng, L.-C., S. Souissi, H.-U. Dahms, Q.-C. Chen & J.-S. Hwang, 2008.  Copepod communities related to water masses in the southwest East China Sea.  Helgoland Marine Research, 62: 153-165.

Tseng, W.-Y., 1972.  The zooplankton community in the surface waters of Taiwan Strait.  Proceedings of the Second Symposium on the Results of the Cooperative Study of the Kuroshio and Adjacent Regions, Tokyo, Japan, September 28-October 1, 1970, Sugawara (ed.), pp. 261-268.  Saikon Publ. Co.

Tseng, W.-Y., 1975.  Planktonic copepods from the waters off Tansui.  Bulletin of Taiwan Fisheries Research Institute, 24: 1-44.

Tseng, W.- y., S.-h. Hu, T.-s. Chen & C.-h.. Chen, 1971.  Observation on the 24 hour changes in environment, plankton production and their relationships of ocean water at point "S" off the Yu- Tieu Tao.  Bulletin of Taiwan Provincial Fisheries Research Institute, 18: 35-44.

Vervoort, W., 1946.  The Bathypelagic copepoda Calanoida of the Snellius Expedition 1. Families Calanidae, Eucalanidae, Paracalanidae, and Pseudocalanidae.  Temminckia, 8: 1-181.

Vervoort, W.,1951.  Planktonic copepods from the Atlantic sector of the Antartic.  Koninklijke Nederlandse Akademie van Wetenschappen, Afdeeling Natuurkunde, Section 2, 47 (4): 1-156.

Vervoort, W. 1957.  Copepods from Antarctic and Sub- Antarctic plankton samples.  B.A.N.Z. Antarctic Research Expedition Reports- Series, 3: 1-160.

Vervoort, W. 1963.  Pelagic Copepoda.  Part I. Copepoda Calanoida of the families Calanidae up to and including Euchaetidae.  Atlantide Report, 7: 77-194.

Vervoort, W. 1965.  Pelagic Copepoda.  Part II. Copepoda Calanoida of the families Phaennidae up to and including Acartiidae, containing the description of a new speces of Aetideidae.  Atlantide Report, 8: 9-216.

Vives, F., A. Shmeleva, 2007.  Crustacea, Copepodos marinos I. Calanoida.  Fauna Iberica, 29: 1-1152. (In Portuguese)

Wang, J.-Y., J.-L. Tang, H.-Y. Hu, B. Huang, B. & N. Wei, 2008.  Ecological distributional characteristics of zooplankton in Zhejiang sea area estuary.  Journal of Zhejiang Ocean University (Natural Science), 27: 384-389.

Wang, R., S-w. Gao, K., Wang & T. Zuo, 2003.  Zooplankton indication of the Yellow Sea warm current in winter.  Journal of Fisheries of China, 27 (Supp.): 39-48.

Wilson, C. B. 1932a.  The copepod crustaceans of Chesapeake Bay.  Proceedings of the United States National Museum, 80(15)(2915): 1-54, pls. 1-5.

Wilson, C. B. 1932b.  The copepods of the Woods Hole region, Massachusetts. Bulletin of the United States National Museum, 158: 1-635, figs. 1-316, pls. 1-41.

Wilson, C. B. 1950.  Contributions to the biology of the Philippine archipelago and adjacent regions. Copepods gathered by the United States Fisheries Steamer "Albatross" from 1887 to 1909, chiefly in the Pacific Ocean.  Bulletin of the United States National Museum, 100 (14)(4):i-ix, 141-461, pls. 2-36.

With, C., 1915.  Copepoda I. Calanoida Amphascandria.  The Danish Ingolf Expedition, 8 (4): 1-248, pls. 1-8.

Wolfenden, R. D.  1911.  Die marinen Copepoden der Deutschen Sudpolar-Expedition 1901-1903.  II. Die pelagischen Copepoden der Westwinddrift und des Sudlichen Eismeers.  Deutsche Sudpolar-Expedition, 1901-1903, Zoologie, 4: 183-380, pls. 22-40. (In German)

Wong, C.-K., J.-S. Hwang & Q.-C. Chen, 1998.  Taxonomic composition and grazing impact of calanoid copepods in coastal waters near nuclear power plants in northern Taiwan.  Zoological Studies, 37: 330-339.

Yang, G., D. He, C. Wang, Y. Miao & H. Yu, 1999.  Study on the biological oceanography characteristics of planktonic copepods in the waters north of Taiwan Island.  II. Community characteristics.  Acta Oceanologica Sinica, 21(6): 72-80. (In Chinese with English abstract)

Yang, G., D. He, C. Wang, Y. Miao & H. Yu, 2000.  Study on the biological oceanographic characteristics of planktonic copepods in the waters north of Taiwan Province.  III. Indiator species.  Acta Oceanologica Sinica, 22: 93-101. (In Chinese with English abstract)

Yun, J.-Q., H. Huang, L.-M. Huang, K. Z. Li & U.-S. Lian, 2008.  Summer zooplankton in coral reef area of Leizhou Peninsula, China.  Oceanologica et Limnologica Sinica, 39: 131-138. (In Chinese with English abstract)

Zhang, G.-T. & C. K. Wong, 2010.  Changes in the planktonic copepod community in a landlocked bay in the subtropical coastal water of Hong Kong during recovery from eutrophication.  Hydrobiologia, 666: 277-288.

Zhang, J., G.-m. Yang, C.-s. Wang & D.-s. Zhang, 2008.  Ecological study of zooplankton in the waters near the Zhoushan Archipelago. I. Species composition ad quantitative distribution.  Journal of Marine Sciences, 26 (45): 20-28.

Zhang, W., D. Tang, B. Yang, S. Gao, J. Sun, Z. Tao, S. Sun & X. Ning, 2009.  Onshore-offshore variations of copepod community in northern Sout China Sea.  Hydrobiologia, 636: 257-269.

Zhang, W., N. Zhao, Z. Tao & C. Zhang, 2010.  An Illustrated Guide to Marine Planktonic Copepods in China Seas.  Science Press, Beijing, vii+468pp.

Zheng, Z., S. Z. Zhang, S, Li, J. C. Fang, R. Q. Lai, S. L. Zhang, S. Q. Li & Z. Z. Xu, 1965.  Marine Planktonic Copepods of China, Volume 1.  Shanghai Science and Technology Press, Shanghai, ii+209pp. (In Chinese)

Zheng, Z., S. Li, S. G. Li, & B. Y. Chen, 1982a.  Marine Planktonic Copepods of China, Volume 2.  Shanghai Science and Technology Press, Shanghai, ii+162pp.(In Chinese)

Zheng, Z., S. ,G. Li, S. Li & B. Y. Chen, 1982b.  On the distribution of planktonic copepods in Taiwan Strait.  Taiwan Strait, 1: 73-78.(In Chinese with English abstract)

Zhu, C.-S, J. Huang & S. Li, 1991.  Studies on the ecology of copepods in Minnan-Taiwan Bank fishing ground.  *In*: Minnan-Taiwan Bank Fishing Ground Upwelling Ecosystem Study, pp. 440-455, Science Press, Beijing.

Zhu, C.-S., J.-Z. Wu, Y.-S. Lin, M. Su & C.-J. Huang, 1988.  Species composition and quantity distribution of plankton; Appendix: A list of marine organism in the central and northern part of the Taiwan Strait.  *In*: A Comprehensive Oceanographic Survey of the Central and Northern Part of the Taiwan Strait, Fujian Institute of Oceanology (ed.) pp. 259-305, 395-416, Kexuei Zhubanzhe (Science Press), Beijing.

Zhu, L.-Y., J.-S. Kou, B.-J. Qi, X.-Y. Li & X.-F. Xu, 2011.  Study on the community characteristics of planktonic copepods and influential factors in coastal waters south of Qingdao.  Periodical of Ocean University of China, 41(10): 52-60. (In Chinese with English abstract)

Zuo, T., R. Wang, Y. Chen, S. Gao & K. Wang, 2006.  Autumn net copepod abundance and assemblages in relation to water masses on the continental shelf of the Yellow Sea and East China Sea.  Journal of Marine Systems, 59: 159-172.

