
# **TAXONOMY OF CALANOIDA**

General discussion of the taxonomy of calanoid copepods from the levels of genus up to superfamily is available in Boxshall & Halsey (2004).  Some monographs or articles of faunistic studies are important in calanoid taxonomy.  These include Sars (1901-1903, North Atlantic: Norwegian Sea; 1925, North Atlantic and Mediterranean), Breemen (1908, northern North Atlantic and North Sea), With (1915, northern North Atlantic), Rose (1933, Mediterranean and eastern North Atlantic), Giesbrecht (1893, Mediterranean Sea), Vives & Shmeleva (2007, eastern North Atlantic off Portugal), Vervoort (1963, 1965, eastern tropical Atlantic), Harding (2004, western N Atlantic off Canada), Wilson (1932a and b, western North Atlantic: Woods Hole region and Chesapeake Bay), Owre & Foyo (1967, Florida Current, western North Atlantic), Campos Hernández & Suárez Morales (1994, Gulf of Mexico & Caribbean Sea), Bradford-Grieve et al. (1999, western South Atlantic), Gardner & Szabo (1982, eastern N Pacific off Canada), Esterly (1905-1913, eastern North Pacific, San Diego region), Palomares et al. (1998, eastern North Pacific off Mexico), Brodsky (1950, western North Pacific), Mori (1937), Tanaka (1956-1965), Tanaka & Omori (1968-1992), and Chihara & Murano (1997) (North Pacific adjacent to Japan), Scott (1909, tropical western Pacific), Greenwood (1976-1982, South Pacific: Moreton Bay, Australia), Bradford (Bradford-Grieve since 1994) and associates (1980-1999, South Pacific adjacent to New Zealand), Vervoort (1946, Indo-W. Pacific), Mulyadi (2004: Indo-West Pacific), Sewell (1929, 1932, 1947, Indian Ocean), Vervoort (1951, 1957, Antarctic), Wolfenden (1911, Antarctic).  Razouls et al. (2005-2019) set up a website ([http://copepodes.obs-banyuls.fr/en](*http://copepodes.obs-banyuls.fr/en*)) to cover taxonomy and distribution of marine copepods of the world.

Taxonomic studies on marine copepods of the China seas were reviewed by Chen, Q. (1986) and Shih & Young (1995).  Major taxonomic studies on the marine Calanoida of the area are Shen & Bai (1956), Shen & Lee (1963), Chen, Q. & Zhang (1965), Zheng et al. (1965), Chen, Q. & Shen (1974), Chen, Q. & Zhang, 1974), Lian & Lin (1978), Zheng et al. (1982a), Zhang, W. et al. (2010), and Lian et al. (2018).  Species lists of the China seas are available, e.g., Shen & Bai (1956), Chen, B. (1984), Shih & Young (1995), Chen, Q. (2008), Lian & Lin (2008), Song, X. et al. (2010), Zhang, W.et al. (2010), and Lian et al. (2018) for the Bohai Sea; Chen, Q. & Zhang (1965), Zheng et al. (1965, 1982a), Lian & Lin (1978, 1983), Chen, B. (1984), Shih & Young (1995), Wang, Gao et al. (2003), Zuo et al. (2006), Chen, Q. (2008), Lian & Lin (2008), Zhang, W. et al. (2010), Zhu et al. (2011), Chen, H. et al. (2015), Chen, H. & Liu (2015), and Lian et al. (2018) for the Yellow Sea; Chen, Q. & . Zhang (1965), Zheng et al. (1965), Tan (1969 & 1971), Tseng, W. et al. (1971), Lian & Lin (1978), Zheng et al. (1982a), Lian & Lin (1983), Chen, B. (1984), He & Yang (1990), Meng et al. (1990, 1991, 1992, 1993), Lin & Nakamura (1992), Shih & Young (1995), Shih & Chiu (1998), Yang et al. (1999, 2000), Hwang, Tu et al. (2004), Lo et al. (2004b), Hwang & Wong (2005), Hwang, Souissi, et al. (2006), Zuo et al. (2006), Dur et al. (2007), Chen, Q. (2008), Lan et al. (2008a & b), Lian & Lin (2008), Tseng, L., Souissi et al. (2008), Wang, J, Tang. et al. (2008), Zhang, J.et al. (2008), Jin et al. (2009), Zhang, W. et al. (2010), Tseng, Dahm et al. (2012), Tseng, L, Hung et al. (2013), Chen, H. & Liu (2015), and Luo et al. (2016), and Lian et al. (2018) for the East China Sea. Tan (1969 & 1971), Wong et al. (1998), Hsiao, Lee et al. (2004), Hwang, Tu et al. (2004), Liao et al. (2006), Dur et al. (2007), Lin, J.-h. (2007), Lan, Lee, Liao et al. (2008b), Lee, Liu & Su (2009), Lee, Shih & Hsu (2009), Hsiao, Fang et al. (2011), Hsiao, Ka et al. (2011), and Ka & Hwang (2011) for East of Taiwan. Zheng et al. (1965), Tan (1969 & 1971), Tseng, W (1972, 1975), Zheng et al. (1982a & b), Chen, B. (1984), Li & Huang (1984), Huang & Chen (1985), Lin & Lian, (1988), Zhu et al. (1988), Dai et al. (1991), Zhu et al. (1991), Huang et al. (2000), Lo et al. (2001), Hsieh& Chiu (2002), Hwang et al. (2003), Hsieh, Chiu & Shih (2004), Lan et al. (2004), Lo et al. (2004a), Hsieh, Chen & Chiu (2005), Hwang, J.-S., S.Souis, et al. (2006), Dur et al. (2007), Lian & Lin (2008), Tseng, Kumar et al. (2008b), Chen, Q. (2008), Hwang, Souis, et al. (2009), Hwang, Kumar et al. (2010), Lan , Lee, Liao, Lee (2009), Hsiao et al. (2011), Ka & Hwang (2011), Dahm, Tseng et al. (2012) and Lian et al. (2018) for the Taiwan Strait; and Wilson (1950), Rose (1955 & 1956), Shen & Lee (1963), Zheng et al. (1965), Chen, Q. & Shen (1974), Chen, Q. & S. Zhang (1974), Chen, Q. (1982), Zheng et al. (1982a), Chen, B. (1984), Chen, Q., Zhang & Yun (1987), Chen, R et al. (1988), Shih & Young (1995), Hwang et al. (2000), Chen, Q., Wong et al. (2003), Lee, C. (2003), Lee & Chen (2003), Tan, Y. et al. (2004), Hwang & Wong (2005), Hwang et al. (2007), Chen, Q. (2008), Hsu et al. (2008), Lian & Lin (2008), Tseng, L., H. Dahms et al. (2008), Tseng, L., R. Kumar et al. (2008a), Yun et al. (2008), Zhang, Tang et al. (2009), Chang et al. (2010), Zhang, G. & Wong (2010), Lin et al. (2011), Lo et al. (2014), Li, K. et al. (2016) , Lian et al. (2018) for the South China Sea.

Research in calanoid copepods of the China seas has been relatively active in the last two decades.  Using Shih and Young (1995) as a reference point, the numbers of family, genus and species reported from the China seas have been increased significantly from 27, 72 and 295 in 1995, respectively, to 30, 106 and 562 currently. 

